"""Initial revision

Revision ID: 341c9dda0a4e
Revises: 
Create Date: 2022-03-05 00:42:56.800122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341c9dda0a4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
