"""Add friends table

Revision ID: 50a8f8ab611b
Revises: e89d137a465e
Create Date: 2022-03-05 13:37:40.143467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50a8f8ab611b'
down_revision = 'e89d137a465e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend',
    sa.Column('relation_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('friend_col1', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('friend_col2', postgresql.UUID(as_uuid=True), nullable=True),
    sa.PrimaryKeyConstraint('relation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friend')
    # ### end Alembic commands ###
